// <auto-generated />
using System;
using CompanyContractsWebAPI.DbRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyContractsWebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260125131124_Conatracts_and_ContractsDone")]
    partial class Conatracts_and_ContractsDone
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyContractsWebAPI.Models.DB.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Done_Sum")
                        .HasColumnType("numeric");

                    b.Property<int>("Good_Count")
                        .HasColumnType("integer");

                    b.Property<string>("Good_Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Total_Sum")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId")
                        .IsUnique();

                    b.ToTable("contract", "dbo");
                });

            modelBuilder.Entity("CompanyContractsWebAPI.Models.DB.ContractDone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Contract_Id")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<decimal>("Done_Amount")
                        .HasColumnType("money");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Contract_Id");

                    b.HasIndex("IntegrationId")
                        .IsUnique();

                    b.ToTable("contract_done", "dbo");
                });

            modelBuilder.Entity("CompanyContractsWebAPI.Models.DB.ContractDone", b =>
                {
                    b.HasOne("CompanyContractsWebAPI.Models.DB.Contract", "Contract")
                        .WithMany()
                        .HasForeignKey("Contract_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");
                });
#pragma warning restore 612, 618
        }
    }
}
