// <auto-generated />
using CompanyContractsWebAPI.DbRepositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CompanyContractsWebAPI.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241222103556_CompanyGoodPrice_Tables_Create")]
    partial class CompanyGoodPrice_Tables_Create
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CompanyContractsWebAPI.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("company", "dbo");
                });

            modelBuilder.Entity("CompanyContractsWebAPI.Models.CompanyGoodPrice", b =>
                {
                    b.Property<int>("Company_Id")
                        .HasColumnType("integer")
                        .HasColumnOrder(1);

                    b.Property<int>("Good_Id")
                        .HasColumnType("integer")
                        .HasColumnOrder(2);

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("Company_Id", "Good_Id");

                    b.HasIndex("Good_Id");

                    b.ToTable("company_good_price", "dbo");
                });

            modelBuilder.Entity("CompanyContractsWebAPI.Models.Good", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Measurement_Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("good", "dbo");
                });

            modelBuilder.Entity("CompanyContractsWebAPI.Models.CompanyGoodPrice", b =>
                {
                    b.HasOne("CompanyContractsWebAPI.Models.Company", "Company")
                        .WithMany("CompanyGoodPrices")
                        .HasForeignKey("Company_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompanyContractsWebAPI.Models.Good", "Good")
                        .WithMany("CompanyGoodPrices")
                        .HasForeignKey("Good_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Good");
                });

            modelBuilder.Entity("CompanyContractsWebAPI.Models.Company", b =>
                {
                    b.Navigation("CompanyGoodPrices");
                });

            modelBuilder.Entity("CompanyContractsWebAPI.Models.Good", b =>
                {
                    b.Navigation("CompanyGoodPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
